### ISSUE TITLE
USER STORY: View A Post

### ISSUE THREAD

**Issue by ScottA27** [ScottA27/Portfolio-Project-5#10]
As a **user** I can **view the details of a single post** so that **I can learn more about it**

### Acceptance Criteria:
***
* Acceptance Criteria 1: Post page shows details of a single post
* Acceptance Criteria 2: All users can see the post whether logged in or out
* Acceptance Criteria 3: Post details include: image, title, content, team, stadium,
location and tags

### Tasks
***
- [x] Design post page
- [x] Create HTML, CSS, JSX
- [x] Create API request
- [x] Test functionality
