### ISSUE TITLE
USER STORY: Authentication - Sign Up

### ISSUE THREAD

**Issue by ScottA27** [ScottA27/Portfolio-Project-5#3]
As a **user** I can **create a new account** so that **I can access all the features for signed up users**

### Acceptance Criteria:
***
* Acceptance Criteria 1: Nav link on sign up in navbar, routes to sign up page
* Acceptance Criteria 2: Sign up page contains a sign up form with username, password
and password confirm fields
* Acceptance Criteria 3: Validation for each of the input fields in the form
* Acceptance Criteria 4: If the user enters valid information a new user is created

### Tasks
***
- [x] Design sign up page
- [x] Create bootstrap sign up form with HTML, CSS, JSX 
- [x] Create API requests
- [x] Test functionality
