### ISSUE TITLE
USER STORY: Authentication - Sign In

### ISSUE THREAD

**Issue by ScottA27** [ScottA27/Portfolio-Project-5#4]
As a **user** I can **sign in to the app** so that **I can access functionality for logged in users**

### Acceptance Criteria:
***
* Acceptance Criteria 1: Login link shown in navbar for logged out users
* Acceptance Criteria 2: Login link routes users to the login page
* Acceptance Criteria 3: Login page has a login form, if the user enters valid credentials they
are logged in
* Acceptance Criteria 4: Once logged in users are redirected to the home page

### Tasks
***
- [x] Create login page
- [x] Create bootstrap login form with HTML, CSS, JSX
- [x] Create API request
- [x] Test functionality
